recipe: default.v1

assistant_id: restobot_assistant

language: vi

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 50
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50
  - name: FallbackClassifier
    threshold: 0.3

policies:
  - name: RulePolicy
    priority: 1
  - name: MemoizationPolicy
    priority: 2
  - name: UnexpecTEDIntentPolicy
    priority: 3
  - name: TEDPolicy
    priority: 4