recipe: default.v1

language: vi

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
  - name: EntitySynonymMapper
  - name: FallbackClassifier

policies:
  - name: RulePolicy
  - name: TEDPolicy