recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: restobot_assistant

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
# Tokenizer for Vietnamese
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 150
     constrain_similarities: true
     model_confidence: linear_norm
     loss_type: cross_entropy
     ranking_length: 10
     use_masked_language_model: false
     BILOU_flag: true
     number_of_transformer_layers: 4
     transformer_size: 256
     drop_rate: 0.1
     drop_rate_attention: 0.0
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 150
     constrain_similarities: true
   - name: FallbackClassifier
     threshold: 0.3
     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 5
    priority: 2
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "utter_default"
    enable_fallback_prediction: True
    priority: 6
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 150
    priority: 1
  - name: TEDPolicy
    max_history: 5
    epochs: 150
    constrain_similarities: true
    loss_type: cross_entropy
    ranking_length: 10
    number_of_transformer_layers: 4
    transformer_size: 256
    drop_rate: 0.1
    drop_rate_attention: 0.0
    use_masked_language_model: false
    priority: 3