version: "3.1"

recipe: default.v1
language: vi

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
  - name: EntitySynonymMapper
  - name: FallbackClassifier

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy